name: ${DOCKER_STACK_NAME}

services:

  node:
    build:
      context: ./docker/
      args:
        - TEST_USER_NAME
        - TEST_USER_ID
        - TEST_GIT_NAME
        - TEST_GIT_EMAIL
    privileged: true
    restart: "no"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/home/${TEST_USER_NAME}/works/"
      - "/home/${HOST_USER_NAME}/.ssh/config:/home/${TEST_USER_NAME}/.ssh/config:ro"
