name: ${DOCKER_STACK_NAME}

services:

  test:
    build:
      context: ./docker/
      args:
        - TEST_USER_NAME
        - TEST_USER_ID
        - TEST_GIT_NAME
        - TEST_GIT_EMAIL
    restart: "no"
    networks:
      - net_web
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.http.routers.${DOCKER_STACK_NAME}-dev-frontend.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.routers.${DOCKER_STACK_NAME}-dev-frontend.rule=Host(`${WEBAPP_DOMAIN}`)
      - traefik.http.services.${DOCKER_STACK_NAME}-dev-frontend.loadbalancer.server.port=${WEBAPP_PORT}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./:/home/${TEST_USER_NAME}/works/"
      - "/home/${HOST_USER_NAME}/.ssh/config:/home/${TEST_USER_NAME}/.ssh/config:ro"
      - "/home/${HOST_USER_NAME}/.ssh/key.gitea:/home/${TEST_USER_NAME}/.ssh/key.gitea:ro"
      - "/home/${HOST_USER_NAME}/.ssh/key.github:/home/${TEST_USER_NAME}/.ssh/key.github:ro"
      - "/home/${HOST_USER_NAME}/.ssh/key.home:/home/${TEST_USER_NAME}/.ssh/key.home:ro"

networks:
  net_web:
    name: ${TRAEFIK_NETWORK}
    external: true
