version: '3'
services:

  test:
    build: 
      context: ./docker/
      args:
        - USER_NAME=aa
    volumes:
      - "./:/home/aa/works/"
      - "/home/aa/.bash_aliases:/home/aa/.bash_aliases:ro"
      - "/home/aa/.ssh/config:/home/aa/.ssh/config:ro"
      - "/home/aa/.ssh/key.internal:/home/aa/.ssh/key.internal:ro"
      - "/home/aa/.ssh/key.internal.pub:/home/aa/.ssh/key.internal.pub:ro"
      - "/home/aa/.ssh/key.github:/home/aa/.ssh/key.github:ro"
      - "/home/aa/.ssh/key.github.pub:/home/aa/.ssh/key.github.pub:ro"
      - "/home/aa/.ssh/key.gitea:/home/aa/.ssh/key.gitea:ro"
      - "/home/aa/.ssh/key.gitea.pub:/home/aa/.ssh/key.gitea.pub:ro"
